- name: Install VScode repo without apt_key
  block:
    - name: Get apt key
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: /etc/apt/keyrings/microsoft.asc

    - name: Install repo
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/microsoft.asc] https://packages.microsoft.com/repos/code stable main
        state: present

- name: Install vscode
  apt:
    name:
      - code
    state: latest
    update_cache: true