- name: Add apt signing key
  ansible.builtin.apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present

- name: Add repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main
    state: present

- name: Install vscode
  apt:
    pkg: "code"
    state: latest
    update_cache: true