---
- name: Clone dotfiles repo
  ansible.builtin.git:
    repo: 'git@github.com:evsor/.dotfiles.git'
    dest: "{{ home_dir }}/.dotfiles"
    key_file: "{{ home_dir }}/.ssh/id_rsa"

- name: Change owner
  ansible.builtin.file:
    path: "{{ home_dir }}/.dotfiles"
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    recurse: true

- name: Run stow
  shell: "stow . --dir={{ home_dir }}/.dotfiles --target {{ home_dir }} --verbose=2"
  register: link_created
  changed_when: 'link_created.stderr is search("LINK: ")'