---
- name: Install Helm repositories
  kubernetes.core.helm_repository:
    repo_name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
    state: present
  loop: "{{ tools_helm_repos }}"
  loop_control:
    label: "{{ item.name }}"

- name: Install Helm plugins
  kubernetes.core.helm_plugin:
    plugin_path: "{{ item.url }}"
    state: present
  loop: "{{ tools_helm_plugins }}"
  loop_control:
    label: "{{ item.name }}"
