---
- name: Install from external repositories
  become: true
  become_user: root
  become_method: sudo
  block:
    - name: Install repo
      ansible.builtin.deb822_repository:
        name: "{{ item.name }}"
        uris: "{{ item.uris }}"
        suites: "{{ item.suites }}"
        components: "{{ item.components | default(omit) }}"
        architectures: "{{ item.architectures | default(omit) }}"
        signed_by: "{{ item.signed_by }}"
        state: present
      loop: "{{ tools_apt_repos }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Install packages
      ansible.builtin.apt:
        name: "{{ tools_apt_packages | map(attribute='name') | list }}"
        state: latest
        update_cache: true

- name: Install tools from GitHub releases
  become: true
  become_user: root
  become_method: sudo
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    mode: '755'
  loop: "{{ tools_binaries }}"
  loop_control:
    label: "{{ item.name }}"

- name: Install tools from GitHub releases but it's tarballs
  become: true
  become_user: root
  become_method: sudo
  ansible.builtin.unarchive:
    src: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    mode: '755'
    remote_src: true
  loop: "{{ tools_tarballs }}"
  loop_control:
    label: "{{ item.name }}"

- name: Install tools from .deb packages
  become: true
  become_user: root
  become_method: sudo
  ansible.builtin.apt:
    deb: "{{ item.url }}"
  loop: "{{ tools_debs }}"
  loop_control:
    label: "{{ item.name }}"

- name: Create additional directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    state: directory
    mode: '0755'
  loop: "{{ tools_directories }}"
  loop_control:
    label: "{{ item.path }}"

- name: Include Helm specific tasks
  ansible.builtin.include_tasks: helm.yml

- name: Include docker specific tasks
  ansible.builtin.include_tasks: docker.yml
