---
keyrings_dir: "/etc/apt/keyrings"
kubectl_version: 1.31
kubeswitch_version: 0.9.2
k9s_version: 0.32.7
sops_version: 3.9.2
yq_version: 4.45.1
fzf_version: 0.58.0
qbec_version: 0.16.3
jb_version: 0.6.0