---
- name: Install base packages
  apt:
    name: #Keep in alphabetical order
      - curl
      - git
      - htop
      - python3-pip
    state: present
    update_cache: yes

- name: Install base snaps
  community.general.snap:
    name: #Keep in alphabetical order
      - chromium
    state: present