---
- name: Add repositories
  ansible.builtin.apt_repository:
    repo: ppa:phoerious/keepassxc # keepassxc repository
    state: present

- name: Install base packages
  apt:
    name: #Keep in alphabetical order
      - apt-transport-https
      - curl
      - dropbox
      - git
      - htop
      - keepassxc
      - python3-pip
      - terminator
    state: present
    update_cache: yes

- name: Install base snaps
  community.general.snap:
    name: #Keep in alphabetical order
      - chromium
    state: present