---
- name: Add apt repositories
  ansible.builtin.apt_repository:
    repo: ppa:phoerious/keepassxc # keepassxc repository
    state: present

- name: Install base packages
  become: true
  become_user: root
  become_method: sudo
  apt:
    name: #Keep in alphabetical order
      - arc-theme
      - apt-transport-https
      - ca-certificates
      - curl
      - dropbox
      - fzf
      - git
      - gnome-tweaks
      - gnome-shell-extension-manager
      - gnupg
      - htop
      - keepassxc
      - python3-pip
      - software-properties-common
      - stow
      - terminator
      - x11-utils
    state: present
    update_cache: yes

- name: Install base snaps
  community.general.snap:
    name: #Keep in alphabetical order
      - chromium
    state: present

- name: Generate SSH key
  openssh_keypair:
    path: "{{ home_dir }}/.ssh/id_rsa"
    size: 2048
    owner: "{{ local_user }}"

- name: Add GitHub to known hosts
  ansible.builtin.known_hosts:
    path: /etc/ssh/ssh_known_hosts
    name: github.com
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    state: present